# Generated by Django 5.2.5 on 2025-10-10 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
