# Generated by Django 5.2.1 on 2025-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_category_services_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='social_links',
            field=models.URLField(blank=True, default=dict),
        ),
    ]
