# Generated by Django 5.2.5 on 2025-10-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_services_category_delete_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonies',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
